CREATE TABLE `churches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`denomination` varchar(100) NOT NULL,
	`pastorName` varchar(255),
	`address` text,
	`city` varchar(100) NOT NULL,
	`state` varchar(2),
	`phone` varchar(20),
	`whatsapp` varchar(20),
	`createdBy` int,
	`isVerified` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `churches_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `emergency_contacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`registrationId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`relationship` enum('esposa','mae','pai','irmao','irma','filho','filha','tio','tia','avo','outro') NOT NULL,
	`relationshipOther` varchar(100),
	`phone` varchar(20) NOT NULL,
	`whatsapp` varchar(20) NOT NULL,
	`email` varchar(320),
	`isAuthorizationContact` int NOT NULL DEFAULT 0,
	`isPrimaryContact` int NOT NULL DEFAULT 0,
	`city` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `emergency_contacts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `message_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`templateType` enum('autorizacao_familiar','autorizacao_lider','confirmacao','lembrete') NOT NULL,
	`targetAudience` enum('esposa','mae_responsavel','lider_espiritual','todos') NOT NULL,
	`content` text NOT NULL,
	`isActive` int NOT NULL DEFAULT 1,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `message_templates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `registrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`regType` enum('participante','servo') NOT NULL,
	`event` varchar(100) NOT NULL DEFAULT 'TOP 1870',
	`regStatus` enum('draft','submitted','approved','rejected') NOT NULL DEFAULT 'draft',
	`fullName` varchar(255) NOT NULL,
	`cpf` varchar(14) NOT NULL,
	`rg` varchar(20),
	`birthDate` varchar(10) NOT NULL,
	`maritalStatus` enum('solteiro','casado','divorciado','viuvo','uniao_estavel') NOT NULL,
	`phone` varchar(20) NOT NULL,
	`whatsapp` varchar(20) NOT NULL,
	`email` varchar(320) NOT NULL,
	`address` text NOT NULL,
	`neighborhood` varchar(100) NOT NULL,
	`city` varchar(100) NOT NULL,
	`state` varchar(2) NOT NULL,
	`zipCode` varchar(9) NOT NULL,
	`profession` varchar(100),
	`shirtSize` enum('PP','P','M','G','GG','XG','XXG') NOT NULL,
	`bloodType` enum('A+','A-','B+','B-','AB+','AB-','O+','O-','nao_sei') NOT NULL,
	`hasAllergy` int NOT NULL DEFAULT 0,
	`allergyDetails` text,
	`hasMedication` int NOT NULL DEFAULT 0,
	`medicationDetails` text,
	`hasChronicDisease` int NOT NULL DEFAULT 0,
	`chronicDiseaseDetails` text,
	`hasPhysicalRestriction` int NOT NULL DEFAULT 0,
	`physicalRestrictionDetails` text,
	`hasFoodRestriction` int NOT NULL DEFAULT 0,
	`foodRestrictionDetails` text,
	`healthInsurance` varchar(100),
	`healthObservations` text,
	`churchId` int,
	`churchName` varchar(255),
	`denomination` varchar(100),
	`spiritualLeaderId` int,
	`memberSince` varchar(10),
	`ministryRole` varchar(100),
	`baptized` int NOT NULL DEFAULT 0,
	`baptizedHolySpirit` int NOT NULL DEFAULT 0,
	`servantRole` varchar(100),
	`previousTops` int DEFAULT 0,
	`legendaryNumber` varchar(20),
	`userId` int,
	`leadId` int,
	`orderId` int,
	`submittedAt` timestamp,
	`approvedAt` timestamp,
	`approvedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `registrations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `spiritual_leaders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` enum('Pastor','Apostolo','Bispo','Presbitero','Discipulador','Lider','Padre','Outro') NOT NULL,
	`name` varchar(255) NOT NULL,
	`churchId` int,
	`phone` varchar(20) NOT NULL,
	`whatsapp` varchar(20) NOT NULL,
	`email` varchar(320),
	`createdBy` int,
	`isVerified` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `spiritual_leaders_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `whatsapp_messages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`registrationId` int NOT NULL,
	`contactId` int NOT NULL,
	`recipientType` enum('familiar','lider_espiritual') NOT NULL,
	`recipientName` varchar(255) NOT NULL,
	`recipientWhatsapp` varchar(20) NOT NULL,
	`templateId` int,
	`messageContent` text NOT NULL,
	`msgStatus` enum('queued','sent','delivered','read','responded','failed','expired') NOT NULL DEFAULT 'queued',
	`sentAt` timestamp,
	`deliveredAt` timestamp,
	`readAt` timestamp,
	`respondedAt` timestamp,
	`responseType` enum('text','audio','image','video','document'),
	`responseContent` text,
	`responseStorageKey` varchar(255),
	`authorizationStatus` enum('pending','authorized','denied','unclear') DEFAULT 'pending',
	`authorizationNotes` text,
	`processedBy` int,
	`processedAt` timestamp,
	`retryCount` int DEFAULT 0,
	`expiresAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `whatsapp_messages_id` PRIMARY KEY(`id`)
);
