import { useEffect, useState } from "react";
import { useRoute, Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CheckCircle, Download, Share2, ArrowLeft, QrCode, Loader2 } from "lucide-react";

export default function ConfirmacaoInscricao() {
  const [, params] = useRoute("/inscricao/confirmacao/:id");
  const registrationId = params?.id ? parseInt(params.id) : null;
  const { user } = useAuth();

  const { data: checkin, isLoading: loadingCheckin } = trpc.checkin.getByRegistration.useQuery(
    { registrationId: registrationId! },
    { enabled: !!registrationId && !!user }
  );

  const generateMutation = trpc.checkin.generate.useMutation();

  const [qrGenerated, setQrGenerated] = useState(false);

  useEffect(() => {
    if (registrationId && user && !checkin && !loadingCheckin && !qrGenerated) {
      // Auto-generate QR code if not exists (admin only)
      // For regular users, QR will be generated by admin
    }
  }, [registrationId, user, checkin, loadingCheckin, qrGenerated]);

  const handleDownloadQR = () => {
    if (!checkin?.qrCodeDataUrl) return;
    const link = document.createElement("a");
    link.href = checkin.qrCodeDataUrl;
    link.download = `qrcode-inscricao-${registrationId}.png`;
    link.click();
  };

  const handleShareQR = async () => {
    if (!checkin?.qrCodeDataUrl) return;
    try {
      const response = await fetch(checkin.qrCodeDataUrl);
      const blob = await response.blob();
      const file = new File([blob], `qrcode-inscricao-${registrationId}.png`, { type: "image/png" });
      
      if (navigator.share) {
        await navigator.share({
          title: "QR Code - TOP 1870 Destemidos Pioneiros",
          text: "Meu QR Code de check-in para o TOP 1870",
          files: [file],
        });
      } else {
        handleDownloadQR();
      }
    } catch {
      handleDownloadQR();
    }
  };

  if (!registrationId) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center p-4">
        <Card className="max-w-md w-full">
          <CardContent className="p-6 text-center">
            <p className="text-muted-foreground">Inscrição não encontrada.</p>
            <Link href="/">
              <Button variant="outline" className="mt-4">
                <ArrowLeft className="w-4 h-4 mr-2" /> Voltar ao início
              </Button>
            </Link>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-zinc-900 flex items-center justify-center p-4">
      <div className="max-w-lg w-full space-y-6">
        {/* Success Header */}
        <div className="text-center space-y-3">
          <div className="w-20 h-20 mx-auto bg-green-500/20 rounded-full flex items-center justify-center">
            <CheckCircle className="w-10 h-10 text-green-500" />
          </div>
          <h1 className="text-2xl font-bold text-foreground">Inscrição Confirmada!</h1>
          <p className="text-muted-foreground">
            Sua inscrição no TOP 1870 — Destemidos Pioneiros foi realizada com sucesso.
          </p>
        </div>

        {/* QR Code Card */}
        <Card className="border-border/50 bg-card/80 backdrop-blur">
          <CardHeader className="text-center pb-2">
            <CardTitle className="text-lg flex items-center justify-center gap-2">
              <QrCode className="w-5 h-5 text-orange-500" />
              Seu QR Code de Check-in
            </CardTitle>
            <p className="text-sm text-muted-foreground">
              Apresente este código no dia do evento para realizar o check-in
            </p>
          </CardHeader>
          <CardContent className="flex flex-col items-center space-y-4">
            {loadingCheckin ? (
              <div className="w-64 h-64 flex items-center justify-center bg-muted/20 rounded-lg">
                <Loader2 className="w-8 h-8 animate-spin text-muted-foreground" />
              </div>
            ) : checkin?.qrCodeDataUrl ? (
              <>
                <div className="bg-white p-4 rounded-xl shadow-lg">
                  <img
                    src={checkin.qrCodeDataUrl}
                    alt="QR Code de Check-in"
                    className="w-56 h-56"
                  />
                </div>
                <p className="text-xs text-muted-foreground font-mono">
                  Token: {checkin.qrCodeToken.substring(0, 12)}...
                </p>
                <div className="flex gap-3">
                  <Button variant="outline" size="sm" onClick={handleDownloadQR}>
                    <Download className="w-4 h-4 mr-2" /> Baixar
                  </Button>
                  <Button variant="outline" size="sm" onClick={handleShareQR}>
                    <Share2 className="w-4 h-4 mr-2" /> Compartilhar
                  </Button>
                </div>
              </>
            ) : (
              <div className="w-64 h-64 flex flex-col items-center justify-center bg-muted/20 rounded-lg space-y-3">
                <QrCode className="w-12 h-12 text-muted-foreground/50" />
                <p className="text-sm text-muted-foreground text-center px-4">
                  Seu QR Code será gerado pela equipe organizadora. Você receberá uma notificação quando estiver pronto.
                </p>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Instructions */}
        <Card className="border-border/50 bg-card/80 backdrop-blur">
          <CardContent className="p-5 space-y-3">
            <h3 className="font-semibold text-foreground">Próximos passos:</h3>
            <ol className="space-y-2 text-sm text-muted-foreground list-decimal list-inside">
              <li>Aguarde a confirmação da equipe organizadora</li>
              <li>Você receberá uma mensagem no WhatsApp com instruções</li>
              <li>No dia do evento, apresente o QR Code na entrada</li>
              <li>Traga documento de identidade com foto</li>
            </ol>
          </CardContent>
        </Card>

        {/* Actions */}
        <div className="flex flex-col sm:flex-row gap-3">
          <Link href="/" className="flex-1">
            <Button variant="outline" className="w-full">
              <ArrowLeft className="w-4 h-4 mr-2" /> Voltar ao início
            </Button>
          </Link>
          <a
            href={`https://wa.me/${import.meta.env.VITE_WHATSAPP_NUMBER || "5569999999999"}?text=Olá! Acabei de me inscrever no TOP 1870. Inscrição #${registrationId}`}
            target="_blank"
            rel="noopener noreferrer"
            className="flex-1"
          >
            <Button className="w-full bg-green-600 hover:bg-green-700">
              Falar no WhatsApp
            </Button>
          </a>
        </div>
      </div>
    </div>
  );
}
